"""Copies the mod's ToolDefinition declarations out of the Module sources into ToolDefs.g.cs,
so the probe offers the model exactly the words the game does. Run before building:
    python tools/probe/extract_tools.py
Only const strings and `public static readonly ... = ...;` statements are copied; the Module
files themselves reference TaleWorlds and cannot be compiled here."""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
TOOLS = ROOT / "src" / "ImmersiveAI.Module" / "Tools"
FILES = ["WorldRecall", "FieldCraft", "WebWisdom", "ChronicleTool", "NuptialTool", "DoorTool", "CradleTool"]


def statement_end(src, start):
    """Index just past the ';' that ends the statement starting at `start`, skipping strings."""
    i, depth, n = start, 0, len(src)
    while i < n:
        c = src[i]
        if c == '"':
            if i > 0 and src[i - 1] == '@':
                i += 1
                while i < n and not (src[i] == '"' and (i + 1 >= n or src[i + 1] != '"')):
                    i += 2 if src[i] == '"' else 1
            else:
                i += 1
                while i < n and src[i] != '"':
                    i += 2 if src[i] == '\\' else 1
        elif c == "'":
            i += 1
            while i < n and src[i] != "'":
                i += 2 if src[i] == '\\' else 1
        elif src.startswith("//", i):
            i = src.index("\n", i)
        elif c in "({[":
            depth += 1
        elif c in ")}]":
            depth -= 1
        elif c == ';' and depth == 0:
            return i + 1
        i += 1
    raise ValueError("unterminated statement")


out = ["// GENERATED by extract_tools.py from src/ImmersiveAI.Module/Tools — do not edit by hand.",
       "using System.Collections.Generic;", "using ImmersiveAI.Core.Llm;", "",
       "namespace ImmersiveAI.Probe.ToolCopies", "{"]
for name in FILES:
    path = TOOLS / (name + ".cs")
    if not path.exists():
        continue
    src = path.read_text(encoding="utf-8")
    body = []
    for m in re.finditer(r"public const string \w+ = \"[^\"]*\";", src):
        body.append(m.group(0))
    for m in re.finditer(r"public static readonly [^=;]*ToolDefinition[^=;]*=", src):
        body.append(src[m.start():statement_end(src, m.start())])
    out.append(f"    public static class {name}")
    out.append("    {")
    for b in body:
        out.append("        " + b.replace("\n", "\n        "))
    out.append("    }")
    out.append("")
out.append("}")
(pathlib.Path(__file__).parent / "ToolDefs.g.cs").write_text("\n".join(out), encoding="utf-8")
print("wrote ToolDefs.g.cs")
