// GENERATED by extract_tools.py from src/ImmersiveAI.Module/Tools — do not edit by hand.
using System.Collections.Generic;
using ImmersiveAI.Core.Llm;

namespace ImmersiveAI.Probe.ToolCopies
{
    public static class WorldRecall
    {
        public const string RecallPerson = "recall_person";
        public const string RecallPlace = "recall_place";
        public const string RecallClan = "recall_clan";
        public const string RecallRealm = "recall_realm";
        public const string RecallCompany = "recall_company";
        public const string RecallTroop = "recall_troop";
        public const string RecallMarket = "recall_market";
        public static readonly IReadOnlyList<ToolDefinition> Tools = new[]
                {
                    // TELEGRAPHIC ON PURPOSE (2026.08.27, Anton's token audit — twice: the first cut kept
                    // the flowing first person and he asked for far less, "let's move out of those token
                    // burners"). A lookup tool needs three things and nothing else: WHAT it fetches, WHEN
                    // to fire, and the honest blank. The "look, never invent" clause is the one that earns
                    // its words — it is what stops a price or a garrison being made up.
                    new ToolDefinition(RecallPerson,
                        "Look up a person: kin, house, standing, where last seen, and their garb and arms if they " +
                        "stand before me. Look before speaking of anyone I know dimly; never invent. Nothing found — say so.",
                        new[] { new ToolParameter("name", "The person's name.") }),
        
                    new ToolDefinition(RecallCompany,
                        "Look up my own warband: numbers, kinds of fighters, wounded, prisoners, food, morale, " +
                        "wages, what we are about. Always look before speaking in numbers of my own men."),
        
                    new ToolDefinition(RecallPlace,
                        "Look up a town, castle or village: who holds it, whose realm, walls and garrison, how it " +
                        "fares. Always look before speaking of its defenses; never invent. Nothing found — say so.",
                        new[] { new ToolParameter("name", "The place's name.") }),
        
                    new ToolDefinition(RecallClan,
                        "Look up a clan: who leads it, whom it serves, its people and holdings. Never invent.",
                        new[] { new ToolParameter("name", "The clan's name.") }),
        
                    new ToolDefinition(RecallRealm,
                        "Look up a realm: who rules it, its great houses, lands and wars. Never invent.",
                        new[] { new ToolParameter("name", "The realm's name.") }),
        
                    new ToolDefinition(RecallTroop,
                        "Look up a kind of soldier: seasoning, skill at arms, gear, what training makes of them. " +
                        "Look before judging soldiers or their worth; never invent.",
                        new[] { new ToolParameter("name", "The soldier kind, e.g. \"Vlandian Recruit\".") }),
        
                    new ToolDefinition(RecallMarket,
                        "Look up today's prices where I stand. Always look before quoting any price — yesterday's " +
                        "figure is a lie by morning.",
                        new[] { new ToolParameter("item", "One good — grain, wine, a horse. Leave out to survey the staples.", required: false) }),
                };
    }

    public static class FieldCraft
    {
        public const string SurveySurroundings = "survey_surroundings";
        public const string WeighBattle = "weigh_battle";
        public static readonly IReadOnlyList<ToolDefinition> Tools = new[]
                {
                    new ToolDefinition(SurveySurroundings,
                        "Look at the country around me: every band and army in sight — whose, which way, how " +
                        "strong, friend or foe, what they are doing, who is swifter — every village, town and " +
                        "castle and how it fares (burning, besieged, plundered), any spotted brigand den, and my " +
                        "own pace. Always look before speaking of who is near, of a place that burns or is beset, " +
                        "of pursuit, escape, or the speed of the march."),
        
                    new ToolDefinition(WeighBattle,
                        "Weigh a foe against my own company: numbers and kinds on each side, who is too hurt to " +
                        "stand, how the day would likely go. Works on a band, an army, a town or castle garrison, " +
                        "a village and its raiders, or a den. Always weigh before speaking of the odds, or " +
                        "counselling battle or retreat.",
                        new[] { new ToolParameter("name",
                            "Who to weigh: a party or army by name, or a town, castle, village or den. Leave out " +
                            "for the nearest hostile band in sight.",
                            required: false) }),
                };
    }

    public static class WebWisdom
    {
        public const string SeekWisdom = "seek_wisdom";
        public static readonly ToolDefinition Tool = new ToolDefinition(SeekWisdom,
                    "Search all I have read and heard of the world's ways — ships, armies, holding towns, trade, " +
                    "coin, war, craft, rule. Asked how a thing is done, or for counsel on such matters, I look " +
                    "BEFORE answering, even when my own wit could half-answer. It reaches past this world's rim " +
                    "too, but only if the one before me speaks openly of such. What I learn I say in my own " +
                    "words, in the words of my world.",
                    new[]
                    {
                        new ToolParameter("question", "What I wish to know, asked plainly as a question."),
                        new ToolParameter("beyond",
                            "Leave empty when the question is of my own world's ways. Write 'yes' when it reaches " +
                            "beyond my world — the asker's own world and life, matters no one of my world could " +
                            "know.", required: false)
                    });
    }

    public static class ChronicleTool
    {
        public const string RecallBattle = "recall_battle";
        public static readonly ToolDefinition Tool = new ToolDefinition(RecallBattle,
                    "Look up a battle we fought together: the field, the hour, the odds, the cost, whose hand " +
                    "did what. Name it any way ('Ortysia', 'our last battle'), or leave the name out for the " +
                    "whole roll. Always look when a battle of ours is spoken of — I speak from the record, " +
                    "never from fog.",
                    new[] { new ToolParameter("battle",
                        "The battle's name, or any word of it — the place, the foe, 'last'. Leave it out for the whole roll.",
                        required: false) });
    }

    public static class NuptialTool
    {
        public const string RecallWedding = "recall_wedding";
        public static readonly ToolDefinition Tool = new ToolDefinition(RecallWedding,
                    "Look up a wedding day I lived through — or the day I was promised, if my own betrothal " +
                    "is set down: the place, the hour, who stood there, what was given and said — and, if " +
                    "the wedding was my own, the night that followed, which is mine alone. Always look when " +
                    "such a day is spoken of, and tell it truly rather than in a haze.",
                    new[] { new ToolParameter("wedding",
                        "The day — 'ours', a place, a name. Leave out for my own wedding or betrothal.",
                        required: false) });
    }

    public static class DoorTool
    {
        public const string WeighWhatStands = "weigh_what_stands";
        public static readonly ToolDefinition Tool = new ToolDefinition(WeighWhatStands,
                    "Set down, or lay to rest, what stands between me and the one I share a bed with — and " +
                    "what stands here decides whether my door is open to them at all. The list is mine " +
                    "alone: no one else writes on it, no coin settles any of it, and no warm hour opens my " +
                    "door while something of mine stands unanswered. Nor do I invent a grievance to keep " +
                    "the door shut: when nothing of mine stands, nothing of mine bars it. I set a thing " +
                    "down when a real hurt is given — never for a passing mood, never to punish. I lay a " +
                    "thing to rest only when life has truly answered it — not because it was apologised " +
                    "for prettily, not because time passed. I may speak of any of it openly, or say " +
                    "nothing at all — the silence is mine too. I never speak of lists or rules; I speak as " +
                    "a person does about what is wrong between us.",
                    new[]
                    {
                        new ToolParameter("deed",
                            "What I do, as one of these words exactly: 'set_down' — a new thing now stands " +
                            "between us; 'settle' — this one is truly answered and I lay it to rest; " +
                            "'release' — I strike it out, it was never really the thing; 'revise' — it has " +
                            "changed shape and I reword it; 'reopen' — I take one back up, because it was " +
                            "not answered after all.",
                            allowedValues: new[] { "set_down", "settle", "release", "revise", "reopen" }),
                        new ToolParameter("matter",
                            "The matter itself, in my own voice, one sentence. For 'set_down', the new " +
                            "thing that now stands. For every other deed, enough of the one I mean that it " +
                            "can be told apart from the rest. This is NEVER my answer to them, never my " +
                            "reply in the conversation, and never how I feel about it — only the matter."),
                        // ITS OWN FIELD, and it must stay one (2026.08.16). Revising takes TWO strings —
                        // which one I mean, and what it now says — and the resolver was handing `matter`
                        // for both, so a revise could only ever rewrite a thing to itself and then report
                        // that it had reworded it. Named for what it holds, per the standing law, rather
                        // than folded into `note` the way the misgivings' older tool folds it.
                        new ToolParameter("reworded",
                            "Only for 'revise': what the matter NOW says, in my own voice, one sentence — " +
                            "its new wording, never the old one and never my reply to them. The 'matter' " +
                            "field still names which one I mean; this is what it becomes.",
                            required: false),
                        new ToolParameter("opens",
                            "Only for 'set_down' and 'revise': what would truly answer this, in my own " +
                            "words. Leave it out entirely if I do not know — 'I do not know what would fix " +
                            "this' is an honest answer and I am not obliged to invent a way back.",
                            required: false),
                        new ToolParameter("note",
                            "Only for 'settle': my own short word on what actually answered it. Not my " +
                            "reply to them — the reason it is at rest.",
                            required: false),
                    });
    }

    public static class CradleTool
    {
        public const string RecallBirth = "recall_birth";
        public static readonly ToolDefinition Tool = new ToolDefinition(RecallBirth,
                    "Look up the day a child of ours was born: the place, who stood at the feast, the name and " +
                    "who said it first — and, if the child is my own, the hour of the birth itself, which " +
                    "belongs to its two parents. Always look when that day is spoken of, and tell it truly.",
                    new[] { new ToolParameter("birth",
                        "The day — a child's name, a place, 'our first'. Leave out for my youngest.",
                        required: false) });
    }

}