using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ImmersiveAI.Core.Courtship
{
    /// <summary>
    /// One misgiving a soul holds about a life wed to the player — written by HER OWN hand, in her
    /// own words, mid-conversation (the weigh_misgivings tool), never generated by a matchmaker and
    /// never judged by a ledger. This replaced the checkable quiet-ask DSL on 2026.08.08 (Anton's
    /// call — "no robotic bargains": the old auto-checked gold/skill/trait stoppers made every
    /// courtship a checklist). A misgiving is settled only when SHE marks it laid to rest, with a
    /// light word on what answered it; the world's one remaining hard rail is the station gate,
    /// which lives in <see cref="CourtshipRoad"/> untouched.
    /// </summary>
    public sealed class CourtshipMisgiving
    {
        public string Text { get; set; } = string.Empty;
        /// <summary>True when she has laid it to rest by her own judgment.</summary>
        public bool Settled { get; set; }
        /// <summary>Her light word on what answered it — kept beside the misgiving forever.</summary>
        public string SettledNote { get; set; } = string.Empty;
    }

    /// <summary>
    /// The operations of her own hand over the misgivings list — pure and unit-tested: fuzzy
    /// matching so a restatement lands on the misgiving it means, a cap on what may STAND OPEN at
    /// once (never on a lifetime — the list LIVES: a new true doubt may be set down whenever it
    /// arises, one that proved empty struck out, so a heart can change its mind mid-talk, Anton's
    /// ask 2026.08.08 evening), and "none" honored as a real answer (a clear heart is weighed
    /// too). The game layer owns when the tool rides and where the list lives (NpcMemory).
    /// </summary>
    public static class CourtshipMisgivings
    {
        /// <summary>The most a heart holds OPEN at once — settled ones never block a new doubt.</summary>
        public const int MaxMisgivings = 5;

        // The five things her hand can do. They live here, in Core, because the words are the
        // TOOL'S CONTRACT and the contract is only as good as its reading — see CanonicalAction.
        public const string ActSetDown = "set_down";
        public const string ActSettle = "settle";
        public const string ActRevise = "revise";
        public const string ActReopen = "reopen";
        public const string ActRelease = "release";

        /// <summary>
        /// One of the five words, from whatever the model actually said — empty when nothing close
        /// came. The schema's own enum is the first defense; this is the second, and it exists
        /// because the first did not: caught live on gpt-5.6-terra (2026.08.09), Sibylla laid all
        /// three of her marriage misgivings to rest in one breath — the right texts, honest notes,
        /// perfect timing — under the action word "resolve", and again under "review", and every
        /// one of them fell into the resolver's do-nothing branch. She could never have married
        /// him. A synonym a soul reaches for honestly must land where she meant it.
        /// </summary>
        public static string CanonicalAction(string? raw)
        {
            var a = (raw ?? string.Empty).Trim().ToLowerInvariant()
                .Replace('-', '_').Replace(' ', '_').Trim('_', '.', '"', '\'');
            if (a.Length == 0) return string.Empty;
            switch (a)
            {
                case ActSetDown:
                case "set":
                case "setdown":
                case "write":
                case "write_down":
                case "writedown":
                case "record":
                case "note":
                case "add":
                case "new":
                case "weigh":
                case "weigh_heart":
                case "review":
                case "list":
                case "none":
                    return ActSetDown;

                case ActSettle:
                case "settled":
                case "resolve":
                case "resolved":
                case "answer":
                case "answered":
                case "lay_to_rest":
                case "laytorest":
                case "lay_down":
                case "rest":
                case "close":
                case "closed":
                case "satisfy":
                case "satisfied":
                case "put_to_rest":
                    return ActSettle;

                case ActRelease:
                case "released":
                case "strike":
                case "strike_out":
                case "strikeout":
                case "remove":
                case "delete":
                case "drop":
                case "discard":
                case "withdraw":
                case "retract":
                    return ActRelease;

                case ActRevise:
                case "revised":
                case "reword":
                case "rewrite":
                case "edit":
                case "update":
                case "amend":
                case "change":
                    return ActRevise;

                case ActReopen:
                case "reopened":
                case "unsettle":
                case "restore":
                case "revive":
                case "return":
                    return ActReopen;

                default:
                    return string.Empty;
            }
        }

        /// <summary>The most the list carries in ALL (standing + settled): past this, the oldest
        /// settled ones quietly fade — kept history, not an endless ledger in every sheet.</summary>
        public const int MaxCarried = 10;

        public static int OpenCount(IEnumerable<CourtshipMisgiving>? list) =>
            list?.Count(m => m != null && !m.Settled && !string.IsNullOrWhiteSpace(m.Text)) ?? 0;

        public static int TotalCount(IEnumerable<CourtshipMisgiving>? list) =>
            list?.Count(m => m != null && !string.IsNullOrWhiteSpace(m.Text)) ?? 0;

        /// <summary>Whether a set_down text is the honest "I hold none" answer.</summary>
        public static bool IsNone(string? text)
        {
            var t = (text ?? string.Empty).Trim().Trim('.', '!', '"', '“', '”').ToLowerInvariant();
            return t.Length == 0 || t == "none" || t == "nothing" || t == "no misgivings"
                || t == "i hold none" || t == "my heart is clear";
        }

        // List dressing shed per line: bullets, numbering, stray quotes.
        private static readonly Regex LineDressing = new Regex(
            @"^\s*(?:[-*••]|\d+[\.\)])?\s*", RegexOptions.CultureInvariant);

        /// <summary>
        /// Sets down what she wrote — one misgiving per line (a semicolon-run is honored too),
        /// dressed bullets shed, duplicates and blanks dropped, capped so no more than
        /// <paramref name="max"/> STAND OPEN at once (settled ones never block a new doubt — the
        /// list lives). Past <see cref="MaxCarried"/> in all, the oldest settled quietly fade.
        /// Returns how many were truly added.
        /// </summary>
        public static int SetDown(List<CourtshipMisgiving> list, string? text, int max = MaxMisgivings)
        {
            if (list == null || IsNone(text)) return 0;
            if (max < 1) max = 1;

            var pieces = Pieces(text);

            int added = 0;
            foreach (var piece in pieces)
            {
                if (OpenCount(list) >= max) break;
                if (Restates(list, piece)) continue;
                list.Add(new CourtshipMisgiving { Text = piece });
                added++;
            }

            // History, not a ledger: the oldest settled fade once the whole list outgrows its room.
            while (TotalCount(list) > MaxCarried)
            {
                var oldest = list.FirstOrDefault(m => m != null && m.Settled);
                if (oldest == null) break; // open ≤ max < MaxCarried, so this cannot happen — belt only
                list.Remove(oldest);
            }
            return added;
        }

        /// <summary>
        /// Whether a line she is setting down merely says again something the list already holds —
        /// exactly, or as the plain containment of one inside the other. A soul asked "what stops
        /// you?" often recites her whole list back through the tool (live on gpt-5.6-terra,
        /// 2026.08.09), and a recital must never breed a second copy of a doubt she cannot then
        /// tell apart. Deliberately NOT the lenient word-overlap of <see cref="FindBestMatch"/>:
        /// two truly different doubts in the same register share plenty of words, and swallowing a
        /// real new one is the worse mistake. The length floor keeps a stray word from vanishing
        /// into a long held line.
        /// </summary>
        private static bool Restates(List<CourtshipMisgiving> list, string piece) =>
            Text.LooseMatch.Restates(Held(list), piece);

        private static IEnumerable<string> Held(List<CourtshipMisgiving>? list) =>
            (list ?? new List<CourtshipMisgiving>())
                .Where(m => m != null && !string.IsNullOrWhiteSpace(m.Text)).Select(m => m.Text);

        /// <summary>One misgiving per line, a semicolon-run honored too, dressed bullets and stray
        /// quotes shed. Shared by <see cref="SetDown"/> and <see cref="FindRestated"/> so what is
        /// refused is judged on exactly the pieces that were offered.</summary>
        private static IEnumerable<string> Pieces(string? text) =>
            (text ?? string.Empty).Split('\n')
                .SelectMany(line => line.Contains(';') ? line.Split(';') : new[] { line })
                .Select(p => LineDressing.Replace(p.TrimEnd('\r'), string.Empty).Trim().Trim('"', '“', '”'))
                .Where(p => p.Length > 0);

        /// <summary>
        /// The misgiving she already holds that a rejected <see cref="SetDown"/> merely said again —
        /// null when nothing was refused for that reason. It exists to be READ BACK TO HER: a hand
        /// that answers "you carry that already" without saying which line it means leaves her no
        /// way to tell a swallowed new doubt from a recital of an old one, and the containment rule
        /// is lenient enough (see <see cref="Text.LooseMatch.Restated"/>) that she must have that way.
        /// </summary>
        public static CourtshipMisgiving? FindRestated(List<CourtshipMisgiving>? list, string? text)
        {
            if (list == null || IsNone(text)) return null;
            foreach (var piece in Pieces(text))
            {
                var hit = Text.LooseMatch.Restated(Held(list), piece);
                if (hit != null)
                    return list.FirstOrDefault(m => m != null && m.Text == hit);
            }
            return null;
        }

        /// <summary>
        /// Whether the two hands came in swapped — the misgiving written into her light word, and
        /// the word into the misgiving's place. Caught live on gpt-5.6-terra (2026.08.09) on every
        /// single settle it made: it laid the answer ("he named me free before the whole clan") in
        /// the misgiving's field and the misgiving itself in the note, so nothing matched and
        /// nothing was ever laid to rest. Named fields and clearer wording are the first fix; this
        /// is the one that holds when a model reads them its own way anyway. Deliberately narrow:
        /// it swaps ONLY when what came as the misgiving matches nothing and what came as the note
        /// truly names one.
        /// </summary>
        public static bool HandsCameSwapped(
            List<CourtshipMisgiving>? list, string? which, string? note, bool amongSettled = false)
        {
            if (list == null || string.IsNullOrWhiteSpace(note)) return false;
            Func<CourtshipMisgiving, bool> among = m => m.Settled == amongSettled;
            return FindBestMatch(list, which, among) == null
                && FindBestMatch(list, note, among) != null;
        }

        /// <summary>Strikes the misgiving best matching <paramref name="which"/> out entirely —
        /// not answered, simply no longer truly hers (standing ones first). Returns the removed
        /// one, or null when none matched.</summary>
        public static CourtshipMisgiving? Release(List<CourtshipMisgiving> list, string which)
        {
            if (list == null) return null;
            var hit = FindBestMatch(list, which, m => !m.Settled) ?? FindBestMatch(list, which, m => m.Settled);
            if (hit == null) return null;
            list.Remove(hit);
            return hit;
        }

        /// <summary>Lays the standing misgiving best matching <paramref name="which"/> to rest,
        /// keeping her light word beside it. Returns it, or null when none matched.</summary>
        public static CourtshipMisgiving? Settle(List<CourtshipMisgiving> list, string which, string? note)
        {
            var hit = FindBestMatch(list, which, m => !m.Settled);
            if (hit == null) return null;
            hit.Settled = true;
            hit.SettledNote = (note ?? string.Empty).Trim();
            return hit;
        }

        /// <summary>Rewords the misgiving best matching <paramref name="which"/> into
        /// <paramref name="into"/> (standing ones first). Returns it, or null when none matched
        /// or the new wording is blank — a revise reshapes, it never invents.</summary>
        public static CourtshipMisgiving? Revise(List<CourtshipMisgiving> list, string which, string? into)
        {
            if (string.IsNullOrWhiteSpace(into)) return null;
            var hit = FindBestMatch(list, which, m => !m.Settled) ?? FindBestMatch(list, which, m => m.Settled);
            if (hit == null) return null;
            hit.Text = into!.Trim();
            return hit;
        }

        /// <summary>Takes a settled misgiving up again — it returned to her. Returns it, or null.</summary>
        public static CourtshipMisgiving? Reopen(List<CourtshipMisgiving> list, string which)
        {
            var hit = FindBestMatch(list, which, m => m.Settled);
            if (hit == null) return null;
            hit.Settled = false;
            hit.SettledNote = string.Empty;
            return hit;
        }

        /// <summary>The held misgiving that best matches a restatement of it — leniently: exact,
        /// then containment, then word-overlap above a real majority — among those passing
        /// <paramref name="among"/>. Null when nothing is close enough.</summary>
        /// <summary>
        /// The matching itself lives in <see cref="Text.LooseMatch"/> since 2026.08.15 — the doors
        /// needed exactly this and a second, weaker copy of it would have been the real bug. The
        /// behaviour is unchanged; every rule and every live-probe lesson moved with it.
        /// </summary>
        public static CourtshipMisgiving? FindBestMatch(
            List<CourtshipMisgiving>? list, string? query, Func<CourtshipMisgiving, bool>? among = null) =>
            Text.LooseMatch.Best(
                (list ?? new List<CourtshipMisgiving>()).Where(m => m != null && (among == null || among(m))),
                m => m.Text, query);
    }
}
