using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ImmersiveAI.Core.Courtship
{
    /// <summary>
    /// One misgiving a soul holds about a life wed to the player — written by HER OWN hand, in her
    /// own words, mid-conversation (the weigh_misgivings tool), never generated by a matchmaker and
    /// never judged by a ledger. This replaced the checkable quiet-ask DSL on 2026.08.08 (Anton's
    /// call — "no robotic bargains": the old auto-checked gold/skill/trait stoppers made every
    /// courtship a checklist). A misgiving is settled only when SHE marks it laid to rest, with a
    /// light word on what answered it; the world's one remaining hard rail is the station gate,
    /// which lives in <see cref="CourtshipRoad"/> untouched.
    /// </summary>
    public sealed class CourtshipMisgiving
    {
        public string Text { get; set; } = string.Empty;
        /// <summary>True when she has laid it to rest by her own judgment.</summary>
        public bool Settled { get; set; }
        /// <summary>Her light word on what answered it — kept beside the misgiving forever.</summary>
        public string SettledNote { get; set; } = string.Empty;
    }

    /// <summary>
    /// The operations of her own hand over the misgivings list — pure and unit-tested: fuzzy
    /// matching so a restatement lands on the misgiving it means, a hard cap so the heart never
    /// files a ledger, and "none" honored as a real answer (a clear heart is weighed too). The
    /// game layer owns when the tool rides and where the list lives (NpcMemory).
    /// </summary>
    public static class CourtshipMisgivings
    {
        /// <summary>The most a heart sets down in all — standing and settled together.</summary>
        public const int MaxMisgivings = 5;

        public static int OpenCount(IEnumerable<CourtshipMisgiving>? list) =>
            list?.Count(m => m != null && !m.Settled && !string.IsNullOrWhiteSpace(m.Text)) ?? 0;

        public static int TotalCount(IEnumerable<CourtshipMisgiving>? list) =>
            list?.Count(m => m != null && !string.IsNullOrWhiteSpace(m.Text)) ?? 0;

        /// <summary>Whether a set_down text is the honest "I hold none" answer.</summary>
        public static bool IsNone(string? text)
        {
            var t = (text ?? string.Empty).Trim().Trim('.', '!', '"', '“', '”').ToLowerInvariant();
            return t.Length == 0 || t == "none" || t == "nothing" || t == "no misgivings"
                || t == "i hold none" || t == "my heart is clear";
        }

        // List dressing shed per line: bullets, numbering, stray quotes.
        private static readonly Regex LineDressing = new Regex(
            @"^\s*(?:[-*••]|\d+[\.\)])?\s*", RegexOptions.CultureInvariant);

        /// <summary>
        /// Sets down what she wrote — one misgiving per line (a semicolon-run is honored too),
        /// dressed bullets shed, duplicates and blanks dropped, capped so standing + settled never
        /// pass <paramref name="max"/>. Returns how many were truly added.
        /// </summary>
        public static int SetDown(List<CourtshipMisgiving> list, string? text, int max = MaxMisgivings)
        {
            if (list == null || IsNone(text)) return 0;
            if (max < 1) max = 1;

            var pieces = text!.Split('\n')
                .SelectMany(line => line.Contains(';') ? line.Split(';') : new[] { line })
                .Select(p => LineDressing.Replace(p.TrimEnd('\r'), string.Empty).Trim().Trim('"', '“', '”'))
                .Where(p => p.Length > 0);

            int added = 0;
            foreach (var piece in pieces)
            {
                if (TotalCount(list) >= max) break;
                if (list.Any(m => m != null && Normalize(m.Text) == Normalize(piece))) continue;
                list.Add(new CourtshipMisgiving { Text = piece });
                added++;
            }
            return added;
        }

        /// <summary>Lays the standing misgiving best matching <paramref name="which"/> to rest,
        /// keeping her light word beside it. Returns it, or null when none matched.</summary>
        public static CourtshipMisgiving? Settle(List<CourtshipMisgiving> list, string which, string? note)
        {
            var hit = FindBestMatch(list, which, m => !m.Settled);
            if (hit == null) return null;
            hit.Settled = true;
            hit.SettledNote = (note ?? string.Empty).Trim();
            return hit;
        }

        /// <summary>Rewords the misgiving best matching <paramref name="which"/> into
        /// <paramref name="into"/> (standing ones first). Returns it, or null when none matched
        /// or the new wording is blank — a revise reshapes, it never invents.</summary>
        public static CourtshipMisgiving? Revise(List<CourtshipMisgiving> list, string which, string? into)
        {
            if (string.IsNullOrWhiteSpace(into)) return null;
            var hit = FindBestMatch(list, which, m => !m.Settled) ?? FindBestMatch(list, which, m => m.Settled);
            if (hit == null) return null;
            hit.Text = into!.Trim();
            return hit;
        }

        /// <summary>Takes a settled misgiving up again — it returned to her. Returns it, or null.</summary>
        public static CourtshipMisgiving? Reopen(List<CourtshipMisgiving> list, string which)
        {
            var hit = FindBestMatch(list, which, m => m.Settled);
            if (hit == null) return null;
            hit.Settled = false;
            hit.SettledNote = string.Empty;
            return hit;
        }

        /// <summary>The held misgiving that best matches a restatement of it — leniently: exact,
        /// then containment, then word-overlap above a real majority — among those passing
        /// <paramref name="among"/>. Null when nothing is close enough.</summary>
        public static CourtshipMisgiving? FindBestMatch(
            List<CourtshipMisgiving>? list, string? query, Func<CourtshipMisgiving, bool>? among = null)
        {
            if (list == null || list.Count == 0 || string.IsNullOrWhiteSpace(query)) return null;
            var pool = list.Where(m => m != null && !string.IsNullOrWhiteSpace(m.Text)
                && (among == null || among(m))).ToList();
            if (pool.Count == 0) return null;

            var q = Normalize(query!);
            if (q.Length == 0) return null;

            foreach (var m in pool)
                if (Normalize(m.Text) == q) return m;

            foreach (var m in pool)
            {
                var t = Normalize(m.Text);
                if (t.Length > 0 && (t.Contains(q) || q.Contains(t))) return m;
            }

            var qWords = Words(q);
            CourtshipMisgiving? best = null;
            double bestScore = 0.34;
            foreach (var m in pool)
            {
                var score = Jaccard(qWords, Words(Normalize(m.Text)));
                if (score > bestScore) { bestScore = score; best = m; }
            }
            return best;
        }

        private static string Normalize(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return string.Empty;
            var sb = new StringBuilder(s.Length);
            foreach (var c in s.Trim().ToLowerInvariant())
            {
                if (char.IsLetterOrDigit(c)) sb.Append(c);
                else if (char.IsWhiteSpace(c) && (sb.Length == 0 || sb[sb.Length - 1] != ' ')) sb.Append(' ');
            }
            return sb.ToString().Trim();
        }

        private static HashSet<string> Words(string normalized) =>
            new HashSet<string>(normalized.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries));

        private static double Jaccard(HashSet<string> a, HashSet<string> b)
        {
            if (a.Count == 0 || b.Count == 0) return 0;
            int inter = a.Count(b.Contains);
            int union = a.Count + b.Count - inter;
            return union == 0 ? 0 : (double)inter / union;
        }
    }
}
